FROM nginx:1.24.0-alpine
COPY ./NginxProxyService/nginx.conf /etc/nginx/nginx.conf
COPY ./NginxProxyService/swagger /swagger
COPY ./NginxProxyService/404.html /404.html
VOLUME [ "/nginx_files" ]
VOLUME [ "/front" ]
EXPOSE 8000